FROM centos:centos7

ENV container docker
RUN (cd /lib/systemd/system/sysinit.target.wants/; for i in *; do [ $i == \
systemd-tmpfiles-setup.service ] || rm -f $i; done); \
rm -f /lib/systemd/system/multi-user.target.wants/*;\
rm -f /etc/systemd/system/*.wants/*;\
rm -f /lib/systemd/system/local-fs.target.wants/*; \
rm -f /lib/systemd/system/sockets.target.wants/*udev*; \
rm -f /lib/systemd/system/sockets.target.wants/*initctl*; \
rm -f /lib/systemd/system/basic.target.wants/*;\
rm -f /lib/systemd/system/anaconda.target.wants/*;
VOLUME ["/sys/fs/cgroup"] 
ENTRYPOINT ["/usr/sbin/init"]
CMD ["systemctl restart autofs"]
  

	
# Set Env
RUN yum install -y kde-l10n-Chinese-Traditional.noarch \
	&& yum install -y telnet \
	&& yum install -y vim \
	&& yum install -y wget \
	&& yum install -y ntp \
	&& yum install -y net-tools \
	&& yum install -y libselinux-utils \
	&& yum -y install openssh-clients \
	&& yum clean all

# Enable an NTP Service

RUN yum install ntp -y 
	# && systemctl start ntpd \
	# && systemctl enable ntpd \
	# && systemctl enable ntpd \
	# && hwclock --systohc 	



# Configuring a Local Parcel Repository

RUN yum install httpd -y 
	# && systemctl start httpd \
	# && systemctl enable httpd \
	# && systemctl status httpd 

# CDH 6.3.2 


RUN mkdir -p /var/www/html/cloudera-repos \
	&& wget --recursive --no-parent --no-host-directories https://archive.cloudera.com/cdh6/6.3.2/parcels/ -P /var/www/html/cloudera-repos \
	&& wget --recursive --no-parent --no-host-directories https://archive.cloudera.com/gplextras6/6.3.2/parcels/ -P /var/www/html/cloudera-repos \
	&& chmod -R ugo+rX /var/www/html/cloudera-repos/cdh6 \
	&& chmod -R ugo+rX /var/www/html/cloudera-repos/gplextras6

# Apache Accumulo 

RUN mkdir -p /var/www/html/cloudera-repos \
	&& wget --recursive --no-parent --no-host-directories https://archive.cloudera.com/accumulo-c5/parcels/1.7.2/ -P /var/www/html/cloudera-repos \
	&& chmod -R ugo+rX /var/www/html/cloudera-repos/accumulo-c5

# Apache Spark 2

RUN mkdir -p /var/www/html/cloudera-repos \
	&& wget --recursive --no-parent --no-host-directories https://archive.cloudera.com/spark2/parcels/2.3.0.cloudera3/ -P /var/www/html/cloudera-repos \
	&& chmod -R ugo+rX /var/www/html/cloudera-repos/spark2

# Import the repository signing GPG key

RUN rpm --import https://archive.cloudera.com/cm6/6.3.1/redhat7/yum/RPM-GPG-KEY-cloudera

# Install Cloudera Manager Server

# RUN yum install cloudera-manager-daemons cloudera-manager-agent cloudera-manager-server -y

# Install and Configure MySQL for Cloudera Software

RUN rpm -ivh http://repo.mysql.com/mysql-community-release-el7-5.noarch.rpm \
	# && rpm -ivh mysql-community-release-el7-5.noarch.rpm \
	&& yum -y update\
	&& yum install -y mysql-server 
	# && systemctl enable mysqld \
	# && systemctl start mysqld

# Install mysql jdbc

RUN wget https://dev.mysql.com/get/Downloads/Connector-J/mysql-connector-java-5.1.46.tar.gz \
	&& tar zxvf mysql-connector-java-5.1.46.tar.gz \
	&& mkdir -p /usr/share/java/ \
	&& cd mysql-connector-java-5.1.46 \
	&& cp mysql-connector-java-5.1.46-bin.jar /usr/share/java/mysql-connector-java.jar

# Install openssh server 

RUN	yum install -y openssh-server 
	# && systemctl start sshd \
	# && systemctl enable sshd \
	# && systemctl status sshd
